name: Deploy static site to GitHub Pages

on:
  push:
    branches:
      - principal  # ou 'main' selon ta branche

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .  # ou ./dist si tu compiles avant
